# Generated by Django 4.1.5 on 2023-02-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0007_blog_autor_alter_blog_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titulo',
            new_name='title',
        ),
    ]
