# Generated by Django 4.1.5 on 2023-02-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0011_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='linkPagina',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitioWeb',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='profilePics'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
