# Generated by Django 4.1.5 on 2023-02-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0012_rename_user_perfil_usuario_remove_perfil_linkpagina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='contraseña',
        ),
    ]
